
name: Create and publish a Docker image

on:
  push:
    branches: ['release']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cabal
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: Build image
        run: nix-build docker.nix

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          docker load < result

          IMAGE_ID=ghcr.io/${{ github.repository }}:latest
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag monsuperserveur ${IMAGE_ID}
          docker push ${IMAGE_ID}

